Student: Kevin De Araujo Sanchez
ID: 2022271
CA2 PSI

Github -> https://github.com/2022271-KAS/Problem-Solving-for-Industry---2022

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

*EDA PHASE*

In [29]:
df = pd.read_excel("online_retail_II.xlsx")

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [4]:
df.shape

(525461, 8)

In [9]:
df.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [6]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

In [7]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [10]:
df.duplicated().sum()

6865

In [11]:
df[df['Quantity'] <= 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
525231,538159,21324,NaN,-18,2010-12-09 17:17:00,0.00,NaN,United Kingdom
525232,538158,20892,NaN,-32,2010-12-09 17:17:00,0.00,NaN,United Kingdom
525234,538161,46000S,Dotcom sales,-100,2010-12-09 17:25:00,0.00,NaN,United Kingdom
525235,538162,46000M,Dotcom sales,-100,2010-12-09 17:25:00,0.00,NaN,United Kingdom
525282,C538164,35004B,SET OF 3 BLACK FLYING DUCKS,-1,2010-12-09 17:32:00,1.95,14031.0,United Kingdom

In [12]:
df[df['Price'] <= 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
525231,538159,21324,NaN,-18,2010-12-09 17:17:00,0.0,NaN,United Kingdom
525232,538158,20892,NaN,-32,2010-12-09 17:17:00,0.0,NaN,United Kingdom
525233,538160,20956,NaN,288,2010-12-09 17:18:00,0.0,NaN,United Kingdom
525234,538161,46000S,Dotcom sales,-100,2010-12-09 17:25:00,0.0,NaN,United Kingdom
525235,538162,46000M,Dotcom sales,-100,2010-12-09 17:25:00,0.0,NaN,United Kingdom

In [22]:
df['Description'].value_counts().head(50)

Description
WHITE HANGING HEART T-LIGHT HOLDER    3549
REGENCY CAKESTAND 3 TIER              2212
STRAWBERRY CERAMIC TRINKET BOX        1843
PACK OF 72 RETRO SPOT CAKE CASES      1466
ASSORTED COLOUR BIRD ORNAMENT         1457
60 TEATIME FAIRY CAKE CASES           1400
HOME BUILDING BLOCK WORD              1386
JUMBO BAG RED RETROSPOT               1310
LUNCH BAG RED SPOTTY                  1274
REX CASH+CARRY JUMBO SHOPPER          1232
JUMBO STORAGE BAG SUKI                1220
PACK OF 60 PINK PAISLEY CAKE CASES    1196
WOODEN FRAME ANTIQUE WHITE            1190
LUNCH BAG  BLACK SKULL.               1179
BAKING SET 9 PIECE RETROSPOT          1176
LUNCH BAG SUKI  DESIGN                1157
HEART OF WICKER LARGE                 1151
LOVE BUILDING BLOCK WORD              1142
RED HANGING HEART T-LIGHT HOLDER      1129
SWEETHEART CERAMIC TRINKET BOX        1096
JUMBO SHOPPER VINTAGE RED PAISLEY     1095
JUMBO BAG STRAWBERRY                  1091
HEART OF WICKER SMALL                 1082
HOT WATER BOTTLE TEA AND SYMPATHY     1050
SCOTTIE DOG HOT WATER BOTTLE          1048
VINTAGE SNAP CARDS                    1044
PARTY BUNTING                         1038
LUNCH BAG SPACEBOY DESIGN             1014
PAPER CHAIN KIT 50'S CHRISTMAS        1005
JUMBO  BAG BAROQUE BLACK WHITE        1002
LUNCH BAG WOODLAND                     989
LUNCH BAG CARS BLUE                    987
WOODEN PICTURE FRAME WHITE FINISH      986
HANGING HEART ZINC T-LIGHT HOLDER      968
SET/20 RED SPOTTY PAPER NAPKINS        967
ANTIQUE SILVER TEA GLASS ETCHED        958
CHOCOLATE HOT WATER BOTTLE             958
SET/5 RED SPOTTY LID GLASS BOWLS       952
SMALL POPCORN HOLDER                   951
ZINC METAL HEART DECORATION            947
FELTCRAFT 6 FLOWER FRIENDS             924
72 SWEETHEART FAIRY CAKE CASES         922
GIN + TONIC DIET METAL SIGN            903
PACK OF 72 SKULL CAKE CASES            873
NATURAL SLATE HEART CHALKBOARD         871
6 RIBBONS RUSTIC CHARM                 870
RECYCLING BAG RETROSPOT                869
VICTORIAN GLASS HANGING T-LIGHT        862
POSTAGE                                862
LUNCH BAG PINK RETROSPOT               856
Name: count, dtype: int64

In [23]:
df['InvoiceDate'].min()
df['InvoiceDate'].max()
df.groupby(df['InvoiceDate'].dt.date)['Quantity'].sum()
df.groupby(df['InvoiceDate'].dt.to_period('M'))['Quantity'].sum()

InvoiceDate
2009-12    420088
2010-01    375363
2010-02    368402
2010-03    489370
2010-04    351971
2010-05    364095
2010-06    388253
2010-07    302201
2010-08    451803
2010-09    478262
2010-10    601729
2010-11    673856
2010-12    166648
Freq: M, Name: Quantity, dtype: int64

In [30]:
df['InvoiceDate'].max()
df[df['InvoiceDate'].dt.to_period('M') == '2010-12']['InvoiceDate'].min()
df[df['InvoiceDate'].dt.to_period('M') == '2010-12']['InvoiceDate'].max()

Timestamp('2010-12-09 20:01:00')

In [39]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

daily_demand = df.groupby(df['InvoiceDate'].dt.date)['Quantity'].sum()

weekly_demand = df.groupby(
    pd.Grouper(key='InvoiceDate', freq='W')
)['Quantity'].sum()

monthly_demand = df.groupby(
    pd.Grouper(key='InvoiceDate', freq='ME')
)['Quantity'].sum()

display(daily_demand.head())
display(weekly_demand.head())
display(monthly_demand)

InvoiceDate
2009-12-01    24022
2009-12-02    29942
2009-12-03    44896
2009-12-04    21001
2009-12-05     5033
Name: Quantity, dtype: int64

InvoiceDate
2009-12-06    136455
2009-12-13    111826
2009-12-20    133295
2009-12-27     38512
2010-01-03         0
Freq: W-SUN, Name: Quantity, dtype: int64

InvoiceDate
2009-12-31    420088
2010-01-31    375363
2010-02-28    368402
2010-03-31    489370
2010-04-30    351971
2010-05-31    364095
2010-06-30    388253
2010-07-31    302201
2010-08-31    451803
2010-09-30    478262
2010-10-31    601729
2010-11-30    673856
2010-12-31    166648
Freq: ME, Name: Quantity, dtype: int64

In [40]:
df['Revenue'] = df['Quantity'] * df['Price']

In [53]:
basket_sizes = df.groupby('Invoice')['StockCode'].nunique()

basket_sizes.describe()
(basket_sizes > 1).mean()
basket_sizes.value_counts().head(10)

StockCode
1     8050
2     1789
3     1157
4      894
5      778
6      672
7      632
9      630
11     589
8      577
Name: count, dtype: int64